{
    "name":"Polling",
    "version":"1.0",
    "author":"tedi3231",
    "category":"Maintain",
    "website":"http://www.wedoapp.com",
    "description":"智能楼宇设备巡检系统",
    "data":[
        "polling_view.xml",
    ],
    "depends":[
        "web",
        "hr",
        "product",
    ],
    "js":[
        "static/src/js/highstock_src.js",
        "static/src/js/exporting_src.js",
        "static/src/js/polling.js",

        ],
    "qweb":[
        "static/src/xml/polling.xml",
        ],
    "css":[
        "static/src/css/polling.css",
        ],
    "installable":True,
}
