{
    "name":"Polling",
    "version":"1.0",
    "author":"tedi3231",
    "category":"Maintain",
    "website":"http://www.wedoapp.com",
    "description":"智能楼宇设备巡检系统",
    "data":[
        "polling_view.xml",
        "report/polling_collect_record_report_view.xml"
    ],
    "depends":[
        "web",
        "hr",
        "product",
        "knowledge",
        "document_page",
    ],
    "js":[
        "static/src/js/highstock_src.js",
        "static/src/js/exporting_src.js",
        "static/src/js/polling.js",
        "static/src/js/spin.js",
        "static/src/js/three.js",
        "static/src/js/stats.min.js",
        "static/src/js/OrbitControls.js",
        "static/src/js/MTLLoader.js",
        "static/src/js/OBJMTLLoader.js",
        ],
    "qweb":[
        "static/src/xml/polling.xml",
        ],
    "css":[
        "static/src/css/polling.css",
        ],
    "installable":True,
}
